lib/main.js
src/main.ts

Turn on daemon (multi-user) mode

---

lib/create-darwin-volume.sh
lib/main.js
src/main.ts

MacOS fixes

---

lib/install-nix.sh
lib/main.js
lib/utils.js
src/main.ts

rewrite to bash

---

lib/install-nix.sh

Enable sandbox on darwin

---

lib/install-nix.sh

Add retries when fetching install script.  Fixes #36 .
cc @domenkozar

Add retries when fetching nix install script

---

.github/workflows/test.yml
README.md
action.yml
lib/install-nix.sh
test.nix

Implements #44
This also cleans the install-nix.sh script a bit.
~~!! warning !! not tested yet~~

add extra_nix_config options

---

lib/install-nix.sh

replace deprecated functions

---

README.md

tested with https://github.com/Mic92/dotfiles/runs/1491667409?check_suite_focus=true

README: upgrade flake example

---

.github/workflows/test.yml
README.md

Fix flakes example and add a test

---

README.md

I failed to run workflow and found this :)

README: bump actions

---

README.md

Workaround documentation for #58.

Add FAQ section "How do I add a binary cache?" to README

---

lib/install-nix.sh

Create X number of users where X = 2 * cpu cores

---

lib/install-nix.sh

Fixes #97 
Fixes #104 
cc @lovesegfault for testing

fix #97: install nix config correctly for single-user- mode

---

lib/install-nix.sh

The install script needed a bit of TLC. /cc @flokli

Bash cleanup

---

lib/install-nix.sh

This should hopefully fix #122

fix(lib/install-nix): use elevated privileges to create /etc/nix

---

lib/install-nix.sh

This is a follow-up to 8ae0a9f, carrying an additional fix.

fix: use sudo to place /etc/nix/nix.conf

---

README.md
action.yml
install-nix.sh

I'm starting to see rate limit issues with GitHub Actions more
frequently so I propose to make this option more readily available.

add github_access_token option

---

README.md

Do we need to retag the release for the docs to update on the marketplace?
#154

Update README for v19

---

install-nix.sh

MacOS-12 fix & Nix 2.16.1

---

install-nix.sh

Changelog: https://github.com/NixOS/nix/compare/2.24.8...2.24.9

nix: 2.24.8 -> 2.24.9

---

install-nix.sh

Fixes #227.
Underlying issue fixed in: https://github.com/NixOS/nix/pull/12481

nix: 2.26.2 -> 2.26.3

---

README.md

docs: document how to provide AWS credentials to the nix-daemon
