cachix/install-nix-action

lib/install-nix.sh

Reverts cachix/install-nix-action#26
```
cabal-fmt................................................................An unexpected error has occurred: PermissionError: [Errno 1] Operation not permitted
Check the log at /private/tmp/nix-build-pre-commit-run.drv-0/.cache/pre-commit/pre-commit.log
builder for '/nix/store/8xa7mbxhxnaviv3d8k49r5lq4b0pcdxa-pre-commit-run.drv' failed with exit code 1
```

Revert "Enable sandbox on darwin"

---

action.yml
lib/install-nix.sh

Allow overriding installation URL

---

.github/workflows/test.yml
README.md
action.yml
lib/install-nix.sh

Hey, this adds a new input named `nixpkgs` as default nixpkgs channel.
Resolves https://github.com/cachix/install-nix-action/issues/17.
Resolves https://github.com/cachix/install-nix-action/issues/6.

Add NIX_PATH action input

---

lib/install-nix.sh

Don't run the installer if Nix has already been installed on the host.
We assume that the installed Nix is already in the desired state.
This allows to share a given pipeline between hosted and self-hosted
runners. Usually the self-hosted runners are long-lived and already have
Nix installed.

idempotent installation

---

lib/install-nix.sh

It's unlikely that those env vars will contain whitespaces, but it's
good to keep the script clean.

fix shellcheck warnings

---

lib/install-nix.sh

sudo is not needed when tee'ing into /tmp/nix.conf (proof: `Install nix` on https://github.com/tinkerbell/boots/runs/2901158055?check_suite_focus=true). Without this patch, I am unable to run the `install-nix-action` successfully as I don't have sudo access on the self-hosted runner I'm trying this on, but do have `nix` installed.

Drop unnecessary use of sudo when tee'ing nix.conf

---

lib/install-nix.sh

Tested like with nix-update by applying the following patch
```diff
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
index 852dc7b..9d9dc13 100644
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,7 +7,7 @@ jobs:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
-    - uses: cachix/install-nix-action@v13
+    - uses: supersandro2000/install-nix-action@patch-1
with:
install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
- name: build
```
and running
```ShellSession
sudo rm ~/.cache/act/ -rf && nix-shell -p act --command "sudo -E \$(which act)"
```

Only use nix-daemon when systemd is supported

---

.github/workflows/test.yml
README.md
lib/install-nix.sh

There's not much harm enabling those by default for the CI.
Fix #103

enable flakes & nix-command features by default

---

README.md

version 2.5.0 doesn't seem to exist

fix actions/checkout version in readme.md

---

.github/workflows/test.yml

v0.2.25 was released that includes required fix
https://github.com/nektos/act/releases/tag/v0.2.25
If you would like to drop `setup-go` from the workflow, `act` can be installed via `brew` (it's included on github runners)
but it would depend on https://github.com/Homebrew/homebrew-core/pull/89923 first

ci: switch act to use latest instead of master

---

lib/install-nix.sh

Appending to `$GITHUB_PATH` *prepends* the path to `PATH`, so we need to reverse the order to make sure the user-installed nix comes before the action-installed nix.
(I am aware of the `install_url` trick, but sometimes using `nix-env` is preferable.)

install-nix.sh: ensure user profile comes before default profile in PATH

---

.github/workflows/test.yml

workflows/test.yml use macos-latest again and use nix release with

---

install-nix.sh

The Nix installer produces a significant number of log messages, but usually those messages are not really interesting.  Group those messages under a header, so that GitHub will keep them collapsed by default.
Usually log messages are collapsed under the step title anyway, but if this action is uses inside another composite action, there is no separate step title, therefore the whole Nix installer output is immediately visible when the log section for the outer composite action is expanded.  Adding the group header fixes this problem.
This should also help with complaints like #126.
-----
An example of how the log output looks when `cachix/install-nix-action` is used inside a composite action (expand the “Build” step):
- Before: https://github.com/sigprof/test-workflows/runs/7063391804?che …

install-nix.sh: Collapse log messages

---

install-nix.sh

Hey @domenkozar 👋🏼 
I am using Fedora builders which don't like the daemon option (because of selinux).
I supplied `--no-daemon` to the installer options but saw that the installer still adds those.
This should make it so that we can do single-user installs.
Thanks!

Don't add daemon option if no-daemon is supplied

---

install-nix.sh

`add_config` only takes one argument, not two. This will cause an error when using `github_access_token`:
```
error: illegal configuration line 'access-tokens' in '/etc/nix/nix.conf'
Try 'nix-env --help' for more information.
```
This should (hopefully) fix that. On a sort of related note, the token passed to `github_access_token` will be overwritten if the user also includes `access-tokens = ...` in `extra_nix_config` (instead of merging the two); would it be worth making a PR to document this behavior in the README?

fix typo in github_access_token option

---

action.yml
install-nix.sh

Turns out there is a default github token we can use to talk to github
and avoid the rate limit issues.

Fix rate-limits by using github.token by default

---

README.md

I got distracted :( so this also fixes a typo and makes some other tiny changes that I noticed when I was looking at the README. I can remove those changes or move them to another commit if you'd like. The main difference in content is:
**Before**
> - `github_access_token`: configure nix to pull from github using the given github token. This helps work around rate limit issues.
**After**
> - `github_access_token`: configure Nix to pull from GitHub using the given GitHub token. This helps work around rate limit issues. Has no effect when `access-tokens` is also specified in `extra_nix_config`.
This should hopefully make the option's behavior clear without being verbose, although I'm open to other ideas as well :)

clarify behavior of github_access_token option

---

README.md

Document how to pass env vars to modern nix commands

---

install-nix.sh

Set `TMPDIR` if not already set to workaround potential disk space issues while running builds in a nix shell. See NixOS/nix#395 for more info.
fixes #197

fix: Set TMPDIR to avoid disk space issues

---

install-nix.sh

The token on Enterprise instances is not valid for github.com.
Resolves #196.

fix: don't use the default GitHub token for Enterprise

---

README.md
install-nix.sh

A typical CI machine will have fast internet access, but may not have all the inputs already in the store to rebuild trivial derivations marked with `allowSubstitutes = false`. This leads to expensive cycles of downloads and rebuilds for derivations like the top-level NixOS system, which will be rebuilt from scratch on every CI run, despite being cached.

Enable `always-allow-substitutes` by default

---

install-nix.sh

updated version of nix used by the `install.sh` script
tested this in another project of mine by specifying `install_url` and checking for successful installation using act

nix: 2.20.5 -> 2.21.2

---

.github/workflows/test.yml

ci: fix tests

---

install-nix.sh

This version fixes GC bugs, which can be triggered under memory pressure. Since GitHub runners are at times memory constraint, it would be good to get this out.
Changelog: https://github.com/NixOS/nix/compare/2.24.6...2.24.7

Nix: 2.24.6 -> 2.24.7

---

install-nix.sh

https://github.com/NixOS/nix/security/advisories/GHSA-6fjr-mq49-mm2c
v29 actually doesn't has the fix for this. So the release notes should be updated.

Nix: 2.24.7 -> 2.24.8

---

.github/workflows/test.yml

GitHub has enabled arm64 runners for Open Source projects:
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
This is a naive attempt to turn it on for this project.

GitHub test.yml: add ubuntu-24.04-arm to matrix

---

install-nix.sh

Fixes the following warning:
```
Warning: the flag --darwin-use-unencrypted-nix-store-volume is no longer needed and will be removed in the future.
````

Remove deprecated `--darwin-use-unencrypted-nix-store-volume` flag

---

.github/workflows/test.yml

Done with pin-github-action <https://github.com/mheap/pin-github-action>
1.8.0 using `npx pin-github-action .github/workflows/*.yml`, and then
manually bumping the version tag to the relevant number.
This fixes the issue that it is common practice for GitHub Actions
authors to move major tags when releasing new minor versions.
Dependabot supports updating in the same fashion, bumping the version   
tag when updating the hash.

feat: Pin actions to hashes

---

install-nix.sh

Fix for https://github.com/NixOS/nix/security/advisories/GHSA-qc7j-jgf3-qmhg.

nix: 2.30.0 -> 2.30.1
